[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] Master GeoStore POM                                                [pom]
[INFO] GeoStore - 0 Server Root                                           [pom]
[INFO] GeoStore - Core                                                    [pom]
[INFO] GeoStore - Core - Model                                            [jar]
[INFO] GeoStore - Core - Security                                         [jar]
[INFO] GeoStore - Core - Persistence                                      [jar]
[INFO] GeoStore - Core - Services API                                     [jar]
[INFO] GeoStore - Core - Services implementation                          [jar]
[INFO] GeoStore - Modules                                                 [pom]
[INFO] GeoStore - Modules - REST root                                     [pom]
[INFO] GeoStore - Modules - REST API                                      [jar]
[INFO] GeoStore - Modules - REST services                                 [jar]
[INFO] GeoStore - Modules - REST client                                   [jar]
[INFO] GeoStore - Modules - REST EXTJS services                           [jar]
[INFO] GeoStore - Modules - REST services test                            [war]
[INFO] GeoStore - Modules - REST auditing                                 [jar]
[INFO] GeoStore - Web                                                     [pom]
[INFO] GeoStore - Webapp                                                  [war]
[INFO] 
[INFO] ----------------------< it.geosolutions:geostore >----------------------
[INFO] Building Master GeoStore POM 1.8-SNAPSHOT                         [1/18]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ geostore ---
[INFO] 
[INFO] ---------------< it.geosolutions.geostore:geostore-root >---------------
[INFO] Building GeoStore - 0 Server Root 1.8-SNAPSHOT                    [2/18]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ geostore-root ---
[INFO] 
[INFO] ---------------< it.geosolutions.geostore:geostore-core >---------------
[INFO] Building GeoStore - Core 1.8-SNAPSHOT                             [3/18]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ geostore-core ---
[INFO] 
[INFO] --------------< it.geosolutions.geostore:geostore-model >---------------
[INFO] Building GeoStore - Core - Model 1.8-SNAPSHOT                     [4/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ geostore-model ---
[INFO] Deleting /home/gabsko/breaking-updates/src/core/model/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ geostore-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/gabsko/breaking-updates/src/core/model/src/main/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ geostore-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 20 source files to /home/gabsko/breaking-updates/src/core/model/target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ geostore-model ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/gabsko/breaking-updates/src/core/model/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ geostore-model ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/gabsko/breaking-updates/src/core/model/target/test-classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] --- maven-surefire-plugin:2.4.2:test (default-test) @ geostore-model ---
[INFO] Surefire report directory: /home/gabsko/breaking-updates/src/core/model/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.geosolutions.geostore.core.model.SecurityRuleTest
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1 (file:/home/gabsko/.m2/repository/com/sun/xml/bind/jaxb-impl/2.1.2/jaxb-impl-2.1.2.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int)
WARNING: Please consider reporting this to the maintainers of com.sun.xml.bind.v2.runtime.reflect.opt.Injector$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.172 sec
Running it.geosolutions.geostore.core.model.UserGroupTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.013 sec
Running it.geosolutions.geostore.core.model.AttributeTest
Attribute[id is null, name=testatt, numberValue=42.0, type=NUMBER]
Attribute[id is null, name=testatt, numberValue=42.0, type=NUMBER]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Attribute type="NUMBER">
    <name>testatt</name>
    <value>42.0</value>
</Attribute>

Attribute[id is null, name=testatt, textValue=test, type=STRING]
Attribute[id is null, name=testatt, textValue=test, type=STRING]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Attribute type="STRING">
    <name>testatt</name>
    <value>test</value>
</Attribute>

Attribute[id is null, name=testatt, dateValue=Fri Jan 13 17:38:17 UTC 2023, type=DATE]
Attribute[id is null, name=testatt, dateValue=Fri Jan 13 17:38:17 UTC 2023, type=DATE]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Attribute type="DATE">
    <name>testatt</name>
    <value>2023-01-13T17:38:17.704+0000</value>
</Attribute>

Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.039 sec
Running it.geosolutions.geostore.core.model.UserTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.023 sec
Running it.geosolutions.geostore.core.model.CategoryTest
Category[id=1, name=testatt]
Category[id=1, name=testatt]
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Category>
    <id>1</id>
    <name>testatt</name>
</Category>

Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec
Running it.geosolutions.geostore.core.model.GroupReservedNamesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec

Results :

Tests run: 9, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] -------------< it.geosolutions.geostore:geostore-security >-------------
[INFO] Building GeoStore - Core - Security 1.8-SNAPSHOT                  [5/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ geostore-security ---
[INFO] Deleting /home/gabsko/breaking-updates/src/core/security/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ geostore-security ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ geostore-security ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 26 source files to /home/gabsko/breaking-updates/src/core/security/target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ geostore-security ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ geostore-security ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 7 source files to /home/gabsko/breaking-updates/src/core/security/target/test-classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] --- maven-surefire-plugin:2.4.2:test (default-test) @ geostore-security ---
[INFO] Surefire report directory: /home/gabsko/breaking-updates/src/core/security/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.geosolutions.geostore.core.security.password.PwEncoderTest
ENC --> eUfDgU3d4XXySZ4FSGdIXl+HWKU/Mg1zklCq87hiQz1egHcz5HpMFPrxTvPPFPeV
ENC --> xe+LBqc/N5BSvlk6oBzj6GCCj8fqEN7BiRgiu/HrB1YY3xeo26UQaoQsr3uQA24P
ENC --> T4rAHa2mr/zB861DTsmCBjr1jmMxM4QdWX7EAQpAKV9dDll6NG3IFDAhrwYaxlcf
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.218 sec
Running it.geosolutions.geostore.core.security.ldap.CustomAttributesLdapUserDetailsMapperTest
log4j:WARN No appenders could be found for logger (org.springframework.security.ldap.userdetails.LdapUserDetailsMapper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.019 sec
Running it.geosolutions.geostore.core.security.ExpressionUserMapperTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.046 sec
Running it.geosolutions.geostore.core.security.password.EncodingTest
/home/gabsko/breaking-updates/src/core/security/geostore.jceks@SLTests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.735 sec
Running it.geosolutions.geostore.core.security.SimpleGrantedAuthoritiesMapperTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec
Running it.geosolutions.geostore.core.security.password.MasterPasswordProviderTest
geostore
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.005 sec

Results :

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] -----------< it.geosolutions.geostore:geostore-persistence >------------
[INFO] Building GeoStore - Core - Persistence 1.8-SNAPSHOT               [6/18]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ geostore-persistence ---
[INFO] Deleting /home/gabsko/breaking-updates/src/core/persistence/target
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ geostore-persistence ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:compile (default-compile) @ geostore-persistence ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 22 source files to /home/gabsko/breaking-updates/src/core/persistence/target/classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] >>> hibernate3-maven-plugin:2.2:hbm2ddl (default) > process-resources @ geostore-persistence >>>
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:resources (default-resources) @ geostore-persistence ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 6 resources
[INFO] 
[INFO] <<< hibernate3-maven-plugin:2.2:hbm2ddl (default) < process-resources @ geostore-persistence <<<
[INFO] 
[INFO] 
[INFO] --- hibernate3-maven-plugin:2.2:hbm2ddl (default) @ geostore-persistence ---
[INFO] Configuration XML file loaded: file:/home/gabsko/breaking-updates/src/core/persistence/src/test/resources/hibernate.cfg.xml
[INFO] Hibernate Annotations 3.4.0.GA
[INFO] Hibernate 3.3.1.GA
[INFO] hibernate.properties not found
[INFO] Bytecode provider name : javassist
[INFO] using JDK 1.4 java.sql.Timestamp handling
[INFO] Hibernate Commons Annotations 3.1.0.GA
[INFO] Configuration XML file loaded: file:/home/gabsko/breaking-updates/src/core/persistence/src/test/resources/hibernate.cfg.xml
[INFO] configuring from url: file:/home/gabsko/breaking-updates/src/core/persistence/src/test/resources/hibernate.cfg.xml
[INFO] Configured SessionFactory: null
[INFO] No hibernate properties file loaded.
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.Attribute
[INFO] Bind entity it.geosolutions.geostore.core.model.Attribute on table gs_attribute
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.Category
[INFO] Bind entity it.geosolutions.geostore.core.model.Category on table gs_category
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.Resource
[INFO] Bind entity it.geosolutions.geostore.core.model.Resource on table gs_resource
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.SecurityRule
[INFO] Bind entity it.geosolutions.geostore.core.model.SecurityRule on table gs_security
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.StoredData
[INFO] Bind entity it.geosolutions.geostore.core.model.StoredData on table gs_stored_data
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.User
[INFO] Bind entity it.geosolutions.geostore.core.model.User on table gs_user
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.UserAttribute
[INFO] Bind entity it.geosolutions.geostore.core.model.UserAttribute on table gs_user_attribute
[INFO] Binding entity from annotated class: it.geosolutions.geostore.core.model.UserGroup
[INFO] Bind entity it.geosolutions.geostore.core.model.UserGroup on table gs_usergroup
[INFO] Mapping collection: it.geosolutions.geostore.core.model.Category.resource -> gs_resource
[INFO] Mapping collection: it.geosolutions.geostore.core.model.Resource.attribute -> gs_attribute
[INFO] Mapping collection: it.geosolutions.geostore.core.model.Resource.security -> gs_security
[INFO] Mapping collection: it.geosolutions.geostore.core.model.User.attribute -> gs_user_attribute
[INFO] Mapping collection: it.geosolutions.geostore.core.model.User.security -> gs_security
[INFO] Mapping collection: it.geosolutions.geostore.core.model.UserGroup.security -> gs_security
[INFO] Hibernate Validator not found: ignoring
[INFO] Using dialect: org.hibernate.dialect.H2Dialect
[INFO] Running hbm2ddl schema export
[INFO] writing generated schema to file: /home/gabsko/breaking-updates/src/core/persistence/target/classes/geostore.ddl

    create table gs_attribute (
        id bigint generated by default as identity,
        attribute_date timestamp,
        name varchar(255) not null,
        attribute_number double,
        attribute_text varchar(255),
        attribute_type varchar(255) not null,
        resource_id bigint not null,
        primary key (id),
        unique (name, resource_id)
    );

    create table gs_category (
        id bigint generated by default as identity,
        name varchar(255) not null,
        primary key (id),
        unique (name)
    );

    create table gs_resource (
        id bigint generated by default as identity,
        creation timestamp not null,
        description varchar(10000),
        lastUpdate timestamp,
        metadata varchar(30000),
        name varchar(255) not null,
        category_id bigint not null,
        primary key (id),
        unique (name)
    );

    create table gs_security (
        id bigint generated by default as identity,
        canRead bit not null,
        canWrite bit not null,
        groupname varchar(255),
        username varchar(255),
        group_id bigint,
        resource_id bigint,
        user_id bigint,
        primary key (id),
        unique (resource_id, group_id),
        unique (user_id, resource_id)
    );

    create table gs_stored_data (
        id bigint not null,
        stored_data varchar(10000000) not null,
        resource_id bigint not null,
        primary key (id),
        unique (resource_id)
    );

    create table gs_user (
        id bigint generated by default as identity,
        enabled char(255) not null,
        name varchar(255) not null,
        user_password varchar(255),
        user_role varchar(255) not null,
        primary key (id),
        unique (name)
    );

    create table gs_user_attribute (
        id bigint generated by default as identity,
        name varchar(255) not null,
        string varchar(255),
        user_id bigint not null,
        primary key (id),
        unique (name, user_id)
    );

    create table gs_usergroup (
        id bigint generated by default as identity,
        description varchar(255),
        enabled char(255) not null,
        groupName varchar(255) not null,
        primary key (id),
        unique (groupName)
    );

    create table gs_usergroup_members (
        user_id bigint not null,
        group_id bigint not null,
        primary key (user_id, group_id)
    );

    alter table gs_attribute 
        add constraint FKA33E7B09410D3892 
        foreign key (resource_id) 
        references gs_resource;

    alter table gs_resource 
        add constraint FK9612B2016A775292 
        foreign key (category_id) 
        references gs_category;

    alter table gs_security 
        add constraint FKE2F965339EC981B7 
        foreign key (group_id) 
        references gs_usergroup;

    alter table gs_security 
        add constraint FKE2F9653362224F72 
        foreign key (user_id) 
        references gs_user;

    alter table gs_security 
        add constraint FKE2F96533410D3892 
        foreign key (resource_id) 
        references gs_resource;

    alter table gs_stored_data 
        add constraint FK8EDDBBF3410D3892 
        foreign key (resource_id) 
        references gs_resource;

    alter table gs_user_attribute 
        add constraint FK7F7AFADB62224F72 
        foreign key (user_id) 
        references gs_user;

    alter table gs_usergroup_members 
        add constraint FKFDE460DB9EC981B7 
        foreign key (group_id) 
        references gs_usergroup;

    alter table gs_usergroup_members 
        add constraint FKFDE460DB62224F72 
        foreign key (user_id) 
        references gs_user;
[INFO] schema export complete
[INFO] 
[INFO] --- maven-resources-plugin:3.0.1:testResources (default-testResources) @ geostore-persistence ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 7 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.5.1:testCompile (default-testCompile) @ geostore-persistence ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 13 source files to /home/gabsko/breaking-updates/src/core/persistence/target/test-classes
[WARNING] Unable to autodetect 'javac' path, using 'javac' from the environment.
[INFO] 
[INFO] --- maven-surefire-plugin:2.4.2:test (default-test) @ geostore-persistence ---
[INFO] Surefire report directory: /home/gabsko/breaking-updates/src/core/persistence/target/surefire-reports
INFO 2023-01-13 17:38:24.056 org.hibernate.jpa.internal.util.LogHelper::logPersistenceUnitInformation - HHH000204: Processing PersistenceUnitInfo [name: geostore]
INFO 2023-01-13 17:38:24.096 org.hibernate.Version::logVersion - HHH000412: Hibernate ORM core version 5.5.0.Final
WARN 2023-01-13 17:38:24.185 org.hibernate.orm.deprecation::<init> - HHH020100: The Ehcache second-level cache provider for Hibernate is deprecated.  See https://hibernate.atlassian.net/browse/HHH-12441 for details.
INFO 2023-01-13 17:38:24.196 org.hibernate.annotations.common.Version::<clinit> - HCANN000001: Hibernate Commons Annotations {5.1.2.Final}
INFO 2023-01-13 17:38:24.487 org.hibernate.dialect.Dialect::<init> - HHH000400: Using dialect: org.hibernate.dialect.H2Dialect
WARN 2023-01-13 17:38:24.763 net.sf.ehcache.config.ConfigurationFactory::parseConfiguration - No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/home/gabsko/.m2/repository/net/sf/ehcache/ehcache/2.10.6/ehcache-2.10.6.jar!/ehcache-failsafe.xml
Hibernate: drop table if exists public.gs_attribute CASCADE 
Hibernate: drop table if exists public.gs_category CASCADE 
Hibernate: drop table if exists public.gs_resource CASCADE 
Hibernate: drop table if exists public.gs_security CASCADE 
Hibernate: drop table if exists public.gs_stored_data CASCADE 
Hibernate: drop table if exists public.gs_user CASCADE 
Hibernate: drop table if exists public.gs_user_attribute CASCADE 
Hibernate: drop table if exists public.gs_usergroup CASCADE 
Hibernate: drop table if exists public.gs_usergroup_members CASCADE 
Hibernate: drop sequence if exists public.hibernate_sequence
Hibernate: create sequence public.hibernate_sequence start with 1 increment by 1
Hibernate: create table public.gs_attribute (id bigint not null, attribute_date timestamp, name varchar(255) not null, attribute_number double, attribute_text varchar(255), attribute_type varchar(255) not null, resource_id bigint not null, primary key (id))
Hibernate: create table public.gs_category (id bigint not null, name varchar(255) not null, primary key (id))
Hibernate: create table public.gs_resource (id bigint not null, creation timestamp not null, description varchar(10000), lastUpdate timestamp, metadata varchar(30000), name varchar(255) not null, category_id bigint not null, primary key (id))
Hibernate: create table public.gs_security (id bigint not null, canRead boolean not null, canWrite boolean not null, groupname varchar(255), username varchar(255), group_id bigint, resource_id bigint, user_id bigint, primary key (id))
Hibernate: create table public.gs_stored_data (id bigint not null, stored_data varchar(10000000) not null, resource_id bigint not null, primary key (id))
WARN 2023-01-13 17:38:25.111 org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl::handleException - GenerationTarget encountered exception accepting command : Error executing DDL "create table public.gs_stored_data (id bigint not null, stored_data varchar(10000000) not null, resource_id bigint not null, primary key (id))" via JDBC Statement
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table public.gs_stored_data (id bigint not null, stored_data varchar(10000000) not null, resource_id bigint not null, primary key (id))" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlString(SchemaCreatorImpl.java:440)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlStrings(SchemaCreatorImpl.java:424)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:315)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:167)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:136)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:122)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:164)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:81)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:327)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:471)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1410)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at it.geosolutions.geostore.core.dao.BaseDAOTest.<init>(BaseDAOTest.java:75)
	at it.geosolutions.geostore.core.dao.CategoryDAOTest.<init>(CategoryDAOTest.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at junit.framework.TestSuite.createTest(TestSuite.java:60)
	at junit.framework.TestSuite.addTestMethod(TestSuite.java:307)
	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
	at junit.framework.TestSuite.<init>(TestSuite.java:129)
	at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:74)
	at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.<init>(JUnit4TestSet.java:45)
	at org.apache.maven.surefire.junit4.JUnit4DirectoryTestSuite.createTestSet(JUnit4DirectoryTestSuite.java:56)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.locateTestSets(AbstractDirectoryTestSuite.java:96)
	at org.apache.maven.surefire.Surefire.createSuiteFromDefinition(Surefire.java:209)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:338)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:997)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Precision ("10000000") must be between "1" and "1048576" inclusive; SQL statement:
create table public.gs_stored_data (id bigint not null, stored_data varchar(10000000) not null, resource_id bigint not null, primary key (id)) [90150-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:651)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.command.Parser.getInvalidPrecisionException(Parser.java:7343)
	at org.h2.command.Parser.readIfDataType1(Parser.java:7302)
	at org.h2.command.Parser.readIfDataType(Parser.java:7107)
	at org.h2.command.Parser.parseColumnWithType(Parser.java:7089)
	at org.h2.command.Parser.parseColumnForTable(Parser.java:6964)
	at org.h2.command.Parser.parseTableColumnDefinition(Parser.java:10405)
	at org.h2.command.Parser.parseCreateTable(Parser.java:10343)
	at org.h2.command.Parser.parseCreate(Parser.java:7811)
	at org.h2.command.Parser.parsePrepared(Parser.java:1140)
	at org.h2.command.Parser.parse(Parser.java:1068)
	at org.h2.command.Parser.parse(Parser.java:1037)
	at org.h2.command.Parser.prepareCommand(Parser.java:965)
	at org.h2.engine.SessionLocal.prepareLocal(SessionLocal.java:624)
	at org.h2.engine.SessionLocal.prepareCommand(SessionLocal.java:562)
	at org.h2.jdbc.JdbcConnection.prepareCommand(JdbcConnection.java:1111)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:237)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 56 more
Hibernate: create table public.gs_user (id bigint not null, enabled char(255) not null, name varchar(255) not null, user_password varchar(255), user_role varchar(255) not null, primary key (id))
Hibernate: create table public.gs_user_attribute (id bigint not null, name varchar(255) not null, string varchar(255), user_id bigint not null, primary key (id))
Hibernate: create table public.gs_usergroup (id bigint not null, description varchar(255), enabled char(255) not null, groupName varchar(255) not null, primary key (id))
Hibernate: create table public.gs_usergroup_members (user_id bigint not null, group_id bigint not null, primary key (user_id, group_id))
Hibernate: create index public.idx_attribute_name on public.gs_attribute (name)
Hibernate: create index public.idx_attribute_text on public.gs_attribute (attribute_text)
Hibernate: create index public.idx_attribute_number on public.gs_attribute (attribute_number)
Hibernate: create index public.idx_attribute_date on public.gs_attribute (attribute_date)
Hibernate: create index public.idx_attribute_type on public.gs_attribute (attribute_type)
Hibernate: create index public.idx_attribute_resource on public.gs_attribute (resource_id)
Hibernate: alter table public.gs_attribute add constraint UKpt7148tvfohj7dgmxyyq5tjre unique (name, resource_id)
Hibernate: create index public.idx_category_type on public.gs_category (name)
Hibernate: alter table public.gs_category add constraint UK5c8d20r6bikucjcapdd7i36ly unique (name)
Hibernate: create index public.idx_resource_name on public.gs_resource (name)
Hibernate: create index public.idx_resource_description on public.gs_resource (description)
Hibernate: create index public.idx_resource_creation on public.gs_resource (creation)
Hibernate: create index public.idx_resource_update on public.gs_resource (lastUpdate)
Hibernate: create index public.idx_resource_metadata on public.gs_resource (metadata)
Hibernate: create index public.idx_resource_category on public.gs_resource (category_id)
Hibernate: alter table public.gs_resource add constraint UKn024mqjdq1o53j3p7v1if9f0w unique (name)
Hibernate: create index public.idx_security_resource on public.gs_security (resource_id)
Hibernate: create index public.idx_security_user on public.gs_security (user_id)
Hibernate: create index public.idx_security_group on public.gs_security (group_id)
Hibernate: create index public.idx_security_read on public.gs_security (canRead)
Hibernate: create index public.idx_security_write on public.gs_security (canWrite)
Hibernate: create index public.idx_security_username on public.gs_security (username)
Hibernate: create index public.idx_security_groupname on public.gs_security (groupname)
Hibernate: alter table public.gs_security add constraint UKt82wtcwf67q3jkn51ew63gbii unique (user_id, resource_id)
Hibernate: alter table public.gs_security add constraint UKi79yiku7yldr157qelfu78rfo unique (resource_id, group_id)
Hibernate: alter table public.gs_stored_data add constraint UK_repsy09e1h92i6tcjk6o24oh6 unique (resource_id)
WARN 2023-01-13 17:38:25.127 org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl::handleException - GenerationTarget encountered exception accepting command : Error executing DDL "alter table public.gs_stored_data add constraint UK_repsy09e1h92i6tcjk6o24oh6 unique (resource_id)" via JDBC Statement
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table public.gs_stored_data add constraint UK_repsy09e1h92i6tcjk6o24oh6 unique (resource_id)" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlString(SchemaCreatorImpl.java:440)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlStrings(SchemaCreatorImpl.java:424)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:349)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:167)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:136)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:122)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:164)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:81)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:327)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:471)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1410)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at it.geosolutions.geostore.core.dao.BaseDAOTest.<init>(BaseDAOTest.java:75)
	at it.geosolutions.geostore.core.dao.CategoryDAOTest.<init>(CategoryDAOTest.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at junit.framework.TestSuite.createTest(TestSuite.java:60)
	at junit.framework.TestSuite.addTestMethod(TestSuite.java:307)
	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
	at junit.framework.TestSuite.<init>(TestSuite.java:129)
	at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:74)
	at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.<init>(JUnit4TestSet.java:45)
	at org.apache.maven.surefire.junit4.JUnit4DirectoryTestSuite.createTestSet(JUnit4DirectoryTestSuite.java:56)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.locateTestSets(AbstractDirectoryTestSuite.java:96)
	at org.apache.maven.surefire.Surefire.createSuiteFromDefinition(Surefire.java:209)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:338)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:997)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "GS_STORED_DATA" not found; SQL statement:
alter table public.gs_stored_data add constraint UK_repsy09e1h92i6tcjk6o24oh6 unique (resource_id) [42102-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:43)
	at org.h2.command.CommandContainer.update(CommandContainer.java:173)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 56 more
Hibernate: create index public.idx_user_name on public.gs_user (name)
Hibernate: create index public.idx_user_password on public.gs_user (user_password)
Hibernate: create index public.idx_user_role on public.gs_user (user_role)
Hibernate: alter table public.gs_user add constraint UK1nvdvro5ffh89vhe8ut546xcn unique (name)
Hibernate: create index public.idx_user_attribute_name on public.gs_user_attribute (name)
Hibernate: create index public.idx_user_attribute_text on public.gs_user_attribute (string)
Hibernate: create index public.idx_attribute_user on public.gs_user_attribute (user_id)
Hibernate: alter table public.gs_user_attribute add constraint UKmp2h35ne4c79xoj5jfs4jtvse unique (name, user_id)
Hibernate: create index public.idx_usergroup_name on public.gs_usergroup (groupName)
Hibernate: alter table public.gs_usergroup add constraint UKtd6p0q8hs1np9b6mphn1l4msx unique (groupName)
Hibernate: alter table public.gs_attribute add constraint fk_attribute_resource foreign key (resource_id) references public.gs_resource
Hibernate: alter table public.gs_resource add constraint FK4k4vivg9ombpq35y3rwvbvj5a foreign key (category_id) references public.gs_category
Hibernate: alter table public.gs_security add constraint fk_security_group foreign key (group_id) references public.gs_usergroup
Hibernate: alter table public.gs_security add constraint fk_security_resource foreign key (resource_id) references public.gs_resource
Hibernate: alter table public.gs_security add constraint fk_security_user foreign key (user_id) references public.gs_user
Hibernate: alter table public.gs_stored_data add constraint fk_data_resource foreign key (resource_id) references public.gs_resource
WARN 2023-01-13 17:38:25.141 org.hibernate.tool.schema.internal.ExceptionHandlerLoggedImpl::handleException - GenerationTarget encountered exception accepting command : Error executing DDL "alter table public.gs_stored_data add constraint fk_data_resource foreign key (resource_id) references public.gs_resource" via JDBC Statement
org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "alter table public.gs_stored_data add constraint fk_data_resource foreign key (resource_id) references public.gs_resource" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlString(SchemaCreatorImpl.java:440)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.applySqlStrings(SchemaCreatorImpl.java:424)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.createFromMetadata(SchemaCreatorImpl.java:375)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.performCreation(SchemaCreatorImpl.java:167)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:136)
	at org.hibernate.tool.schema.internal.SchemaCreatorImpl.doCreation(SchemaCreatorImpl.java:122)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:164)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:81)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:327)
	at org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:471)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1410)
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:58)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:409)
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:396)
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1845)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1782)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:602)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1154)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:908)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at it.geosolutions.geostore.core.dao.BaseDAOTest.<init>(BaseDAOTest.java:75)
	at it.geosolutions.geostore.core.dao.CategoryDAOTest.<init>(CategoryDAOTest.java:36)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at junit.framework.TestSuite.createTest(TestSuite.java:60)
	at junit.framework.TestSuite.addTestMethod(TestSuite.java:307)
	at junit.framework.TestSuite.addTestsFromTestCase(TestSuite.java:150)
	at junit.framework.TestSuite.<init>(TestSuite.java:129)
	at org.junit.internal.runners.JUnit38ClassRunner.<init>(JUnit38ClassRunner.java:74)
	at org.junit.internal.builders.JUnit3Builder.runnerForClass(JUnit3Builder.java:11)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.apache.maven.surefire.junit4.JUnit4TestSet.<init>(JUnit4TestSet.java:45)
	at org.apache.maven.surefire.junit4.JUnit4DirectoryTestSuite.createTestSet(JUnit4DirectoryTestSuite.java:56)
	at org.apache.maven.surefire.suite.AbstractDirectoryTestSuite.locateTestSets(AbstractDirectoryTestSuite.java:96)
	at org.apache.maven.surefire.Surefire.createSuiteFromDefinition(Surefire.java:209)
	at org.apache.maven.surefire.Surefire.run(Surefire.java:156)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.apache.maven.surefire.booter.SurefireBooter.runSuitesInProcess(SurefireBooter.java:338)
	at org.apache.maven.surefire.booter.SurefireBooter.main(SurefireBooter.java:997)
Caused by: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "GS_STORED_DATA" not found; SQL statement:
alter table public.gs_stored_data add constraint fk_data_resource foreign key (resource_id) references public.gs_resource [42102-206]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:521)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:496)
	at org.h2.message.DbException.get(DbException.java:227)
	at org.h2.message.DbException.get(DbException.java:203)
	at org.h2.command.ddl.AlterTable.update(AlterTable.java:43)
	at org.h2.command.CommandContainer.update(CommandContainer.java:173)
	at org.h2.command.Command.executeUpdate(Command.java:252)
	at org.h2.jdbc.JdbcStatement.executeInternal(JdbcStatement.java:252)
	at org.h2.jdbc.JdbcStatement.execute(JdbcStatement.java:223)
	at org.apache.commons.dbcp.DelegatingStatement.execute(DelegatingStatement.java:264)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 56 more
Hibernate: alter table public.gs_user_attribute add constraint fk_uattrib_user foreign key (user_id) references public.gs_user
Hibernate: alter table public.gs_usergroup_members add constraint FKcuodcud01kw3cqy0emcmh5mgj foreign key (group_id) references public.gs_usergroup
Hibernate: alter table public.gs_usergroup_members add constraint FKoitmticc812u1mao3g7ki1f5y foreign key (user_id) references public.gs_user
INFO 2023-01-13 17:38:25.149 org.hibernate.engine.transaction.jta.platform.internal.JtaPlatformInitiator::initiateService - HHH000490: Using JtaPlatform implementation: [org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform]
INFO 2023-01-13 17:38:25.159 org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean::buildNativeEntityManagerFactory - Initialized JPA EntityManagerFactory for persistence unit 'geostore'

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running it.geosolutions.geostore.core.dao.AttributeDAOTest
INFO 2023-01-13 17:38:25.284 it.geosolutions.geostore.core.dao.AttributeDAOTest::setUp - ################ Running AttributeDAOTest::testSearchAttribute
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.407 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.407 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.416 it.geosolutions.geostore.core.dao.AttributeDAOTest::setUp - ################ Running AttributeDAOTest::testPersistAttribute
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.418 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.418 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.420 it.geosolutions.geostore.core.dao.AttributeDAOTest::setUp - ################ Running AttributeDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.422 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.422 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.148 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.ldap.UserDAOTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.053 sec
Running it.geosolutions.geostore.core.dao.UserGroupDAOTest
INFO 2023-01-13 17:38:25.481 it.geosolutions.geostore.core.dao.UserGroupDAOTest::setUp - ################ Running UserGroupDAOTest::testPersistUserGroup
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.484 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.484 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.485 it.geosolutions.geostore.core.dao.UserGroupDAOTest::setUp - ################ Running UserGroupDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.487 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.487 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.CategoryDAOTest
INFO 2023-01-13 17:38:25.490 it.geosolutions.geostore.core.dao.CategoryDAOTest::setUp - ################ Running CategoryDAOTest::testPersistCategory
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.492 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.492 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.493 it.geosolutions.geostore.core.dao.CategoryDAOTest::setUp - ################ Running CategoryDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.495 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.495 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest
INFO 2023-01-13 17:38:25.498 it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest::setUp - ################ Running ExternalSecurityDAOTest::testPersistSecurityUsingNames
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.500 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.500 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.501 it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest::setUp - ################ Running ExternalSecurityDAOTest::testPersistSecurity
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.503 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.503 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.504 it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest::setUp - ################ Running ExternalSecurityDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.506 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.506 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.SecurityDAOTest
INFO 2023-01-13 17:38:25.509 it.geosolutions.geostore.core.dao.SecurityDAOTest::setUp - ################ Running SecurityDAOTest::testPersistSecurityUsingNames
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.511 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.511 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.512 it.geosolutions.geostore.core.dao.SecurityDAOTest::setUp - ################ Running SecurityDAOTest::testPersistSecurity
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.514 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.514 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.515 it.geosolutions.geostore.core.dao.SecurityDAOTest::setUp - ################ Running SecurityDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.517 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.517 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.UserAttributeDAOTest
INFO 2023-01-13 17:38:25.520 it.geosolutions.geostore.core.dao.UserAttributeDAOTest::setUp - ################ Running UserAttributeDAOTest::testPersistRole
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.521 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.522 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.523 it.geosolutions.geostore.core.dao.UserAttributeDAOTest::setUp - ################ Running UserAttributeDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.524 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.524 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.StoredDataDAOTest
INFO 2023-01-13 17:38:25.527 it.geosolutions.geostore.core.dao.StoredDataDAOTest::setUp - ################ Running StoredDataDAOTest::testPersistData
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.530 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.530 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.531 it.geosolutions.geostore.core.dao.StoredDataDAOTest::setUp - ################ Running StoredDataDAOTest::testBigData
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.532 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.532 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.534 it.geosolutions.geostore.core.dao.StoredDataDAOTest::setUp - ################ Running StoredDataDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.535 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.535 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.011 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.ldap.UserGroupDAOTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.003 sec
Running it.geosolutions.geostore.core.dao.UserDAOTest
INFO 2023-01-13 17:38:25.542 it.geosolutions.geostore.core.dao.UserDAOTest::setUp - ################ Running UserDAOTest::testPersistUser
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.544 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.544 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.545 it.geosolutions.geostore.core.dao.UserDAOTest::setUp - ################ Running UserDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.546 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.547 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.008 sec <<< FAILURE!
Running it.geosolutions.geostore.core.dao.ResourceDAOTest
INFO 2023-01-13 17:38:25.549 it.geosolutions.geostore.core.dao.ResourceDAOTest::setUp - ################ Running ResourceDAOTest::testPersistResource
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.550 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.551 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
INFO 2023-01-13 17:38:25.552 it.geosolutions.geostore.core.dao.ResourceDAOTest::setUp - ################ Running ResourceDAOTest::testCheckDAOs
Hibernate: select resource0_.id as id1_2_, resource0_.category_id as category7_2_, resource0_.creation as creation2_2_, resource0_.description as descript3_2_, resource0_.lastUpdate as lastupda4_2_, resource0_.metadata as metadata5_2_, resource0_.name as name6_2_ from public.gs_resource resource0_
Hibernate: select count(resource0_.id) as col_0_0_ from public.gs_resource resource0_
Hibernate: select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_
WARN 2023-01-13 17:38:25.553 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - SQL Error: 42102, SQLState: 42S02
ERROR 2023-01-13 17:38:25.553 org.hibernate.engine.jdbc.spi.SqlExceptionHelper::logExceptions - Table "GS_STORED_DATA" not found; SQL statement:
select storeddata0_.id as id1_4_, storeddata0_.stored_data as stored_d2_4_, storeddata0_.resource_id as resource3_4_ from public.gs_stored_data storeddata0_ [42102-206]
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.006 sec <<< FAILURE!

Results :

Tests in error: 
  testSearchAttribute(it.geosolutions.geostore.core.dao.AttributeDAOTest)
  testPersistAttribute(it.geosolutions.geostore.core.dao.AttributeDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.AttributeDAOTest)
  testPersistUserGroup(it.geosolutions.geostore.core.dao.UserGroupDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.UserGroupDAOTest)
  testPersistCategory(it.geosolutions.geostore.core.dao.CategoryDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.CategoryDAOTest)
  testPersistSecurityUsingNames(it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest)
  testPersistSecurity(it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.ExternalSecurityDAOTest)
  testPersistSecurityUsingNames(it.geosolutions.geostore.core.dao.SecurityDAOTest)
  testPersistSecurity(it.geosolutions.geostore.core.dao.SecurityDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.SecurityDAOTest)
  testPersistRole(it.geosolutions.geostore.core.dao.UserAttributeDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.UserAttributeDAOTest)
  testPersistData(it.geosolutions.geostore.core.dao.StoredDataDAOTest)
  testBigData(it.geosolutions.geostore.core.dao.StoredDataDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.StoredDataDAOTest)
  testPersistUser(it.geosolutions.geostore.core.dao.UserDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.UserDAOTest)
  testPersistResource(it.geosolutions.geostore.core.dao.ResourceDAOTest)
  testCheckDAOs(it.geosolutions.geostore.core.dao.ResourceDAOTest)

Tests run: 32, Failures: 0, Errors: 22, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Master GeoStore POM 1.8-SNAPSHOT:
[INFO] 
[INFO] Master GeoStore POM ................................ SUCCESS [  0.057 s]
[INFO] GeoStore - 0 Server Root ........................... SUCCESS [  0.021 s]
[INFO] GeoStore - Core .................................... SUCCESS [  0.002 s]
[INFO] GeoStore - Core - Model ............................ SUCCESS [  2.452 s]
[INFO] GeoStore - Core - Security ......................... SUCCESS [  2.874 s]
[INFO] GeoStore - Core - Persistence ...................... FAILURE [  5.159 s]
[INFO] GeoStore - Core - Services API ..................... SKIPPED
[INFO] GeoStore - Core - Services implementation .......... SKIPPED
[INFO] GeoStore - Modules ................................. SKIPPED
[INFO] GeoStore - Modules - REST root ..................... SKIPPED
[INFO] GeoStore - Modules - REST API ...................... SKIPPED
[INFO] GeoStore - Modules - REST services ................. SKIPPED
[INFO] GeoStore - Modules - REST client ................... SKIPPED
[INFO] GeoStore - Modules - REST EXTJS services ........... SKIPPED
[INFO] GeoStore - Modules - REST services test ............ SKIPPED
[INFO] GeoStore - Modules - REST auditing ................. SKIPPED
[INFO] GeoStore - Web ..................................... SKIPPED
[INFO] GeoStore - Webapp .................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.786 s
[INFO] Finished at: 2023-01-13T17:38:25Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.4.2:test (default-test) on project geostore-persistence: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/gabsko/breaking-updates/src/core/persistence/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :geostore-persistence
